apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  sources:
    # 1. Remote Bitnami PostgreSQL chart
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 16.7.4
      helm:
        valueFiles:
          - $values/k8s/helm/postgres/values.yaml

    # 2. Your repo with values file
    - repoURL: https://github.com/TodoFlow-Labs/infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
