apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-authenticated
spec:
  selector:
    matchLabels:
      app: {{ .Values.commandService.name }}
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
