apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ .Values.auth.name}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.commandService.name }}
  jwtRules:
    - issuer: {{ .Values.auth.supabase_url}}
      jwksUri: "{{ .Values.auth.supabase_url}}/auth/v1/keys"
      forwardPayloadHeader: x-jwt-payload
