meshConfig:
  accessLogFile: "/dev/stdout"

pilot:
  autoscaleEnabled: true
  traceSampling: 100.0

# Set trust domain if you're planning to expand with federation later
values:
  global:
    proxy:
      autoInject: enabled
    istioNamespace: istio-system
