auth:
  database: todos
  existingSecret: postgresql
  secretKeys:
    adminPasswordKey: postgres-password
  enablePostgresUser: true
  
  
primary:
  persistence:
    enabled: true
    storageClass: microk8s-hostpath
    size: 3Gi
