apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-infra
  namespace: argocd
spec:
  project: todoflow-lab
  source:
    repoURL: git@github.com:todoflow-labs/infrastructure.git
    targetRevision: main            # or your default branch
    path: charts/todo-infra         # directory containing Chart.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
