apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:todoflow-labs/infrastructure.git
        revision: HEAD
        directories:
          - path: charts/*
          - path: apps/*
  template:
    metadata:
      name: >
        infra-apps-{{path | replace "/" "-"}}
    spec:
      project: todoflow-lab
      source:
        repoURL: git@github.com:todoflow-labs/infrastructure.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
