commandService:
  host: todoflow.local
  name: command-service
  image:
    repository: furlingene/command-service
    tag: latest

  service:
    port: 8080

  env:
    ENV: production
    LOG_LEVEL: debug
    HTTP_ADDR: ":8080"
    METRICS_ADDR: ":9090"
    NATS_URL: "nats://nats.messaging.svc.cluster.local:4222"

domainProcessor:
  name: domain-processor
  image:
    repository: furlingene/domain-processor
    tag: latest
  env:
    ENV: production
    NATS_URL: "nats://nats.messaging.svc.cluster.local:4222"
    LOG_LEVEL: debug
    METRICS_ADDR: ":9090"

  service:
    port: 8080

projectionWorker:
  name: projection-worker
  image:
    repository: furlingene/projection-worker
    tag: latest

  service:
    port: 8080

  env:
    ENV: production
    LOG_LEVEL: debug
    DatabaseURL: "postgres://postgres:pass@postgres.db.svc.cluster.local:5432/todos?sslmode=disable"
    METRICS_ADDR: ":9090"
    NATS_URL: "nats://nats.messaging.svc.cluster.local:4222"
