IngressRoute:
  host: todoflow.local
commandService:
  name: command-service
  image:
    repository: furlingene/command-service
    tag: latest

  service:
    port: 8080
    metricsPort: 9090

  env:
    ENV: production
    LOG_LEVEL: debug
    HTTP_ADDR: ":8080"
    METRICS_ADDR: ":9090"

domainProcessor:
  name: domain-processor
  image:
    repository: furlingene/domain-processor
    tag: latest
  env:
    ENV: production
    LOG_LEVEL: debug
    METRICS_ADDR: ":9090"

  service:
    metricsPort: 9090

projectionWorker:
  name: projection-worker
  image:
    repository: furlingene/projection-worker
    tag: latest

  service:
    metricsPort: 9090

  env:
    ENV: production
    LOG_LEVEL: debug
    METRICS_ADDR: ":9090"

queryService:
  name: query-service
  image:
    repository: furlingene/query-service
    tag: latest

  service:
    port: 8080
    metricsPort: 9090

  env:
    ENV: production
    LOG_LEVEL: debug
    METRICS_ADDR: ":9090"
    HTTP_ADDR: ":8080"

sseUpdates:
  name: sse-updates
  image:
    repository: furlingene/sse-updates
    tag: latest

  service:
    port: 8080
    metricsPort: 9090

  env:
    ENV: production
    LOG_LEVEL: debug
    METRICS_ADDR: ":9090"
    HTTP_ADDR: ":8080"
