global:
  env: production
  logLevel: debug
  natsUrl: "nats://nats.messaging.svc.cluster.local:4222"
  metricsPort: 9090
  databaseUrl: "postgres://postgres:pass@postgres.db.svc.cluster.local:5432/todos?sslmode=disable"

commonEnv: &commonEnv
  ENV: {{ .Values.global.env }}
  LOG_LEVEL: {{ .Values.global.logLevel }}

metricsEnv: &metricsEnv
  METRICS_ADDR: ":{{ .Values.global.metricsPort }}"

databaseEnv: &databaseEnv
  DATABASE_URL: "{{ .Values.global.databaseUrl }}"

natsEnv: &natsEnv
  NATS_URL: "{{ .Values.global.natsUrl }}"

commandService:
  host: todoflow.local
  name: command-service
  image:
    repository: furlingene/command-service
    tag: latest

  service:
    port: 8080
    metricsPort: {{ .Values.global.metricsPort }}

  env:
    <<: [*commonEnv, *natsEnv, *metricsEnv]
    HTTP_ADDR: ":8080"

domainProcessor:
  name: domain-processor
  image:
    repository: furlingene/domain-processor
    tag: latest

  service:
    metricsPort: {{ .Values.global.metricsPort }}

  env:
    <<: [*commonEnv, *natsEnv, *metricsEnv]

projectionWorker:
  name: projection-worker
  image:
    repository: furlingene/projection-worker
    tag: latest

  service:
    metricsPort: {{ .Values.global.metricsPort }}

  env:
    <<: [*commonEnv, *natsEnv, *metricsEnv, *databaseEnv]

queryService:
  name: query-service
  image:
    repository: furlingene/query-service
    tag: latest

  service:
    port: 8080
    metricsPort: {{ .Values.global.metricsPort }}

  env:
    <<: [*commonEnv, *metricsEnv, *databaseEnv]
    HTTP_ADDR: ":8080"
