global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "cockroachdb"
    static_configs:
      - targets: ["cockroachdb:8080"]
    metrics_path: "/_status/vars"

  - job_name: "command-service"
    static_configs:
      - targets: ["command-service:9090"]
    metrics_path: "/metrics"

  - job_name: "domain-processor"
    static_configs:
      - targets: ["domain-processor:9090"]
    metrics_path: "/metrics"