auth:
  strategy: anonymous

deployment:
  accessible_namespaces: ["**"]
  logger:
    log_level: info

external_services:
  prometheus:
    url: http://prometheus.monitoring.svc.cluster.local
  grafana:
    enabled: true
    url: http://grafana.monitoring.svc.cluster.local
  tracing:
    enabled: false

server:
  web_root: /
  metrics_enabled: true

kiali_feature_flags:
  istio_injection_action: true
  istio_upgrade_action: false
  validations:
    ignore: []
