apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.sseUpdates.name } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.sseUpdates.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.sseUpdates.name }}
    spec:
      containers:
        - name: {{ .Values.sseUpdates.name }}
          image: "{{ .Values.sseUpdates.image.repository }}:{{ .Values.sseUpdates.image.tag }}"
          env:
            - name: ENV
              value: "{{ .Values.sseUpdates.env.ENV }}"
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: "{{ .Values.sseUpdates.name }}-config"
