apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.domainProcessor.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.domainProcessor.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.domainProcessor.name }}
    spec:
      containers:
        - name: {{ .Values.domainProcessor.name }}
          image: "{{ .Values.domainProcessor.image.repository }}:{{ .Values.domainProcessor.image.tag }}"
          env:
            - name: ENV
              value: "{{ .Values.domainProcessor.env.ENV }}"
            - name: LOG_LEVEL
              value: "{{ .Values.domainProcessor.env.LOG_LEVEL }}"
            - name: METRICS_ADDR
              value: "{{ .Values.domainProcessor.env.METRICS_ADDR }}"
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: nats-secret
                  key: nats-url
