apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.domainProcessor.name }}
spec:
  selector:
    app: {{ .Values.domainProcessor.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.domainProcessor.service.port }}
