apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.domainProcessor.name }}
spec:
  selector:
    app: {{ .Values.domainProcessor.name }}
  ports:
    - name: metrics
      port: 9090
      targetPort: {{ .Values.domainProcessor.service.metricsPort }}
