apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.queryService.name }}-config"
data:
  config.yaml: |
    http-addr: {{ .Values.queryService.env.HTTP_ADDR }}
    log-level: {{ .Values.queryService.env.LOG_LEVEL }}
    metrics-addr: {{ .Values.queryService.env.METRICS_ADDR }}
    database-url: {{.Values.queryService.env.DATABASE_URL}}
