apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.queryService.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.queryService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.queryService.name }}
    spec:
      containers:
        - name: {{ .Values.queryService.name }}
          image: "{{ .Values.queryService.image.repository }}:{{ .Values.queryService.image.tag }}"
          env:
            - name: ENV
              value: "{{ .Values.queryService.env.ENV }}"
            # - name: LOG_LEVEL
            #   value: "{{ .Values.queryService.env.LOG_LEVEL }}"
            # - name: HTTP_ADDR
            #   value: "{{ .Values.queryService.env.HTTP_ADDR }}"
            # - name: METRICS_ADDR
            #   value: "{{ .Values.queryService.env.METRICS_ADDR }}"
            # - name: DATABASE_URL
            #   value: "{{ .Values.queryService.env.DATABASE_URL }}"
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: "{{ .Values.queryService.name }}-config"
