apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectionWorker.name }}
  labels:
    app: {{ .Values.projectionWorker.name }}
spec:
  selector:
    app: {{ .Values.projectionWorker.name }}
  ports:
    - name: metrics
      port: 9090
      targetPort: {{ .Values.projectionWorker.service.metricsPort }}
