apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.commandService.name }}
spec:
  selector:
    app: {{ .Values.commandService.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.commandService.service.port }}
    - name: metrics
      port: 9090
      targetPort: {{ .Values.commandService.service.metricsPort }}
