apiVersion: v1
kind: Service
metadata:
  name: command-service
spec:
  selector:
    app: command-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.commandService.service.port }}
