---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBYOnu7oM2TinpE+y8XGYP31SEfWamc6apzhK6m3QKJjFVKO3Cu/byDQqlC2rB5tpCskuxJ7MMY5oqt7oy8eE7J/6qm8GHGYR71TiCJ43Pzxj+5oTYY/r8YSr1NOriIuoRnoDYAO19RbuUGkdDdoiaXxUabpNQ1FE0wgaD2Z/kUlqOqWE0X0CPB0eBaiQvXMEs2T18OLuHv+LL9FFJaZL89+Ix14heuWTB2HFLaABpnh7680cSksS/orIHik+P6CKdZEo8Q7X5u0gK/nmVTZguKiyhRNIjHWiT6yvIFEPVDGEqB5wdCp4OR23ZE2KqKZ/VdCzyWpLCKoIOy7G3I5Th4r0suQlMzJcaz+Xc8XP7Z+xdA+RB/AzLPiF/rgv4NVczXCReA/YzvUX77+zrphUNF8oSaE1zwyrFpChRoEfmvzGpHNqOR2+JTI4KmM++OKw76nsy+QoUF1TrQTeq1znD3lGpNnyWFX6LBSFXb3YZnaRUfeW72hI1sLIHImjehuGI+57iXcK3VDMmsu9vNK+216larWswUjuo4em/vRC6qnOg1ijo5qIRJryCP4kIAfnwezhH/mwHVghdEb77iTomtJYZWGOjKfYPhjra2fm6cr5yvSrHEUOwf0nv3RjOZ/uEUG8HYfijZSbIZZcHpdVFBLHd8RQwa2hdzwAG6sZ8YCEazVJtPQY4WHFDK/UI6ZdvZiksz
    admin-user: AgB/XmDGJakyJk52X6Nucr7xSkJZLHbWRzIcmdVqssQHYGtS13Cmoc0hK/6u6yVCqBTBAMLTQQH2rpzkoLSyTpFqAFyjbEoII360wlVzlpNbbI4E/8uxf+JPyAD5S4Oo7u8S5ZocHd4+f6xHkxZQEymMrEWFXANZmC5aua7xk/brnNy4Gtkg+Pw4U5hhHdHgniC50dXrQ7xZKEu6XaaUTG6gxfvQfUmRdZopS+5jeSNoSBOimb1wvW3y3pM9BFW5jdnFXw7tAGVLOTjVyOPR0QddkboWsOLxYLSo7WwQnkRi7a0PM+XZbd2tjUHSmdG0MJyhJvKHEfA20LSAksTgy598/OSSDR69fCzpaU0hKl81ZMmd4irpr48KGDjJBfqC9MDCtKBkhpzQ3eVRNkep2S0jEYGIyp/ECeHlM5izBcOXl8VBlRw4MnyvjIQS+AzerOrifi4a+ygnDWoBzWzwIzgwd16zKc9gjrZHEemSkxKNnu6QJCsqYPLzgbaA+WHkWq4CF5C2Oa3Cmi+EIKmEfGxjA9eqtafB2v+yLnwGgD1oUUQtpa6kp+oj42byc8PPh4d1gzeieEbe29ghiED99XOQDQquSHamkWCtzCB+pmUhfr1S6HBPcXgA7ikKMzc7VE184/vTdir9NO84Ykx86RnG7l6q9oipnLK4TUSnZgtmLsI2DMq5jD4oKHpbKyqF0k6Yh6uAdA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
