---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBYAAsSIs5dLpKZLJCRLG4qKpEXGZNsAbMbAnW7f5pohr5Fexn4TjLYp60RGBp7J0ev87n2itHas2lORI5fs6u73g7vFyscXTVdQKP2j035UxYoX5G0QCG2/d7PwRsMTwqDpFznuf/9wq6YGa5mLTVvdteQCT8lGWVDEceILpWb8zOpMrFe5/RcPOmwBakUBh39F/5AOgYN1lUu1RJJ2avHggWNnsE/0btdBmY7VIFpikYszPcCq4eOYokvCFP7KnEFSglyQl28X7wZv8GFitpq2lHeSuOImcb9Vud2KM6fbUzyc/G3Z/Zqh4vuiB1bl2UHGkWkkEVov1xjZB6K6Zggc7MC0dxBGWMLNREQ0fsPPDCEtvb6agoA1DS/N75hPKlkPierPP2KQCy1MsM+TVCQvMNbQWR/8LDTJSweHvPqej33OdUYTc1H4EHlevetKBE6g4agO1WDS5VFtadVQn8NxICSzmfEXUU3M5lCz4le0Fi84MdJ/ZD5SNSW4SqArQIhAIbIxlogdEVztya5HS5SOCxMKM+9ULHtfnSuAaFgG/p1wwxQp8KDAfWjTRNaoqsAumgXGHCvYKNbs/kO47d3bZjLsM7K4sgdMNF7cZtGGMwbzHMsGVskwUd37ICbooZBl11vwqNC3l6WTpZEEnEGu9vlzuRQkwWSgbohSMjwDQN7v+mPieJHA9ysbDOW+BDMzcy/
    admin-user: AgAhMoS489EJwhOd1j19oN+BR8uoUGbD5b9ksWHqGm1y62ke9B5hVhBGjsZfw64DsthyZXDwAAgNbqTLdQ6xhILxLBWPElShTXX971Y9R7AdDfgjXttozLy9ofy7zglyEHGBBw16kgI2B40YrrURY01VcUVpbj2j1u28FuVbE3NCDHnD8DujMRLHwjaDQ2/xDbdnaRjg1L7/qIK7yCV8lSdJQw3aWxHw7Na529vxv0EL7VWRzf4THP88i0mOSmCLvcz4kW+zKHbvtyj9qBAwf65/AHN5N91fEcPY+r3XZSOBAS5cbh1BcyydjPwaRrirDaaTsx1mrXcZyPuKBz8WlroSvy1IYL4kwZarLFQp6QlwVNUGjqC9G/eiQzMLhaMNcuCwkcarczqsAbTJd0hXxGKDOlf44P2pwulJCyWb9kPfM2/GCMT6iE2trMe6IaHbAh8qh7ZyFbHPZTJNVBa0zKC4HwGb6L7oOBj78NLdRSBEYujDbWZdM3NOnT+sE7PRmxiHaTdHH6z7P2DRsS8qivQNw/KWP9pOeqNyaFvYGQCg0PLMh4iYxa5Ol+OScmDSRd4VbX/xMHgneD9NohgqaevUniRcNnpiPbWkfHGVS1D6PKC6ClI1E6SbNnlgerdZ7z3/YGK1l7YcmwASdknro1XKS/wdSL5dAdrDyasmITIHpvEeXu70dbHYBiHB6uUcDV9JsrytjQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
