traefik:
  service:
    type: ClusterIP
  ingressRoute:
    dashboard:
      enabled: true

linkerd2:
  global:
    namespace: linkerd

nats:
  jetstream:
    enabled: true

cockroachdb:
  statefulset:
    replicas: 1

  podDisruptionBudget:
    enabled: true
    apiVersion: policy/v1     # force the new API
    minAvailable: "50%"

    
hello-world:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
