traefik:
  service:
    type: ClusterIP
  ingressRoute:
    dashboard:
      enabled: true


nats:
  jetstream:
    enabled: true

cockroachdb:
  conf:
    single-node: true

  statefulset:
    replicas: 1

  storage:
    persistentVolume:
      size: 10Gi


hello-world:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
