apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: todoflow
spec:
  headers:
    accessControlAllowOriginList:
      - "*"
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    accessControlAllowHeaders:
      - "*"
    accessControlMaxAge: 300
    addVaryHeader: true
