apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: todoflow
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.tls: "false"
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.commandService.host }}
      http:
        paths:
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.commandService.name }}
                port:
                  number: 80
          - path: /get_todos
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.queryService.name }}
                port:
                  number: 80
