apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: todos-route
  namespace: todoflow
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.IngressRoute.host }}`) && Method(`GET`) && PathPrefix(`/todos`)
      kind: Rule
      middlewares:
            - name: {{ .Values.supabaseJwtProxy.name }}
      services:
        - name: {{ .Values.queryService.name }}
          port: 80
    - match: Host(`{{ .Values.IngressRoute.host }}`) && Method(`OPTIONS`) && PathPrefix(`/todos`)
      kind: Rule
      middlewares:
        - name: cors
      services:
        - name: {{ .Values.queryService.name }}     # Or any service
          port: 80
    - match: Host(`{{ .Values.IngressRoute.host }}`) && (Method(`POST`) || Method(`PUT`) || Method(`DELETE`)) && PathPrefix(`/todos`)
      kind: Rule
      middlewares:
            - name: {{ .Values.supabaseJwtProxy.name }}
      services:
        - name: {{ .Values.commandService.name }}
          port: 80
    - match: Host(`{{ .Values.IngressRoute.host }}`) && PathPrefix(`/events`)
      kind: Rule
      middlewares:
            - name: {{ .Values.supabaseJwtProxy.name }}
      services:
        - name: {{ .Values.sseUpdates.name }}
          port: 80
