---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todoflow-secret
  namespace: todoflow
spec:
  encryptedData:
    database-url: AgC+bL+irIf//4DLQAb4MF0lEVC5uOUZYzpysqHutKbo5EXbv1QeK5lIxXlKUpn/TP1YAukNW/64hKaviX7jcPz61bTMtDxz+kLTWFSPd3i8G8VJBwDFg95Ups6I8z9tNfsLbNQY4PKyRpFfRSSWogUZrt37cqdNs1URWJe1q1teQWujbXWKgOsL8SaY0ugGCaG7IQc2+BznbDsmC+h1cnkNBUcIDELxveuj2OA9xXjdY3kh26/ncs9ZxIAiRSj6yi+o/4iuDCluHz/VI4ZCbZvnVapYKaHRaAmWB2PVUwwF/lo+7YBv+yg8x+lBHfOykJ84FRW35MlpyOgzp63zkxDqQHkzcJz8GFNNrPjrSqiQAkYbyGHNCIshHlF8bfW5rJi4lmarry2ivOHNR4lrUhmRpubgahX6fZXIZlXYU0fEonntUZ12JTT0wluQEE8R+ZCl2CB5yjbIh4yzY5GDq9R4fHKl63AgztmBGxqz84wPnMKpYpvuFT7HLlYz4iuQ2h8q3jlvwikbuT3V2CjnizEUC/GdgMlyWaoMoDQMg0rpO6lhdq92BbLpo2vI8QWF3mRHEJoyvNTv0F9dFRbcx//EpcCG5Wy+VYEHKn9fsvLT7QU4FyeBisww3o1zs9BL4E2RdRl7haOOJBcrobHv2YI1jrOicdyRQ57L4KZ4IuAE2S6Q+xFOmJw1is0HjMnDGhD15t+d2NAl9UlsmJEIzvO3LW8cffpgFLGLm4Gn4MvgFejxCmk795ImSI6AYp4luID3qdZ/zhLFsLSl/KFQQSk24QUujgrjv78s5NDIE1pbbbI=
    nats-url: AgBf1P/rEXTkYhJTK5x3LbQVJlf1yYcn5GhFqj72zdZJ2DNMIkLAsJ0kIZDB91YRNbX9u0lskDL8As4kMdi/W//AQCmHSAG9JjL6+alQaB0zjs0xxuZqfnsQjK3uxXnLNNvn/JSJ54Fs2t2xbNjsjvmluA5nafc20B4o0AGSZM80b7Lbmrd2f1REgbUqmsCs/RSRo4qO8/UDg10n1vWYZqiB/LsBPZVjaP4ZoekfrSK4kPj10LreGaEoR6SHsVhFNNfP7bQbWQNh2vXRuQmwfLaJrasLMhATX0EXI6kPjys0dj+Wnus+06B/7iUW0Nkp6slihzgA9WFTGFRNgytrMgqsmGzq57YlRBaLkIFRY1QQQgAc1vYhRRkjffNxvqW4wFxE1ojOv7G0lozNl5Iqw7leDDoUj6WiXXqSWDjSXHL3bhQbmS5+xkAeKZrlnz9lCKWX6T7FiGxlGELGPs6ZIO6jwBxp3yl1O0webHvSNIkYDcRgwsFH4LAllQnbh63JRToVTYur+UDmLVq2maUAKYM0u+805Fg1swkE2hBhHxeSfyu12scUXfi0LoUQGHkRX9huVjWRSnSzOa+JBHZPKuVAKXeO7L01Y3CLUy7krFcNDKebn6OAluNqUW8rcTKYqKMZ4xbeukWHPHhcUU3fAEX4Upq8BGs/2VMS256VdPOMPZiAAQLbT1DyWA/3PxkSH11qwpWv/BOQKosQ2u/a/yH7oUjqCw6ljTjFad2PCIDCjDcevgYQTeiADz7IJA==
  template:
    metadata:
      creationTimestamp: null
      name: todoflow-secret
      namespace: todoflow
