prometheusSpec:
  serviceMonitorSelectorNilUsesHelmValues: false
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  ruleSelector: {}
  scrapeInterval: 30s

  additionalScrapeConfigs:
    - job_name: "istiod"
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels:
            [__meta_kubernetes_service_name, __meta_kubernetes_namespace]
          action: keep
          regex: istiod;istio-system

    - job_name: "istio-proxies"
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: (.+)
          replacement: $1
        - source_labels:
            [
              __meta_kubernetes_pod_ip,
              __meta_kubernetes_pod_annotation_prometheus_io_port,
            ]
          action: replace
          replacement: $1:$2
          target_label: __address__

serviceMonitors:
  enabled: true
