serviceMonitors:
  enabled: true

serviceMonitorSelector:
  matchLabels:
    release: prometheus

serviceMonitorNamespaceSelector:
  any: true

additionalServiceMonitors:
  - name: istio-pilot
    selector:
      matchLabels:
        app: istiod
    namespaceSelector:
      matchNames:
        - istio-system
    endpoints:
      - port: http-monitoring
        interval: 15s
        path: /metrics
