apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io/
      chart: authentik
      targetRevision: 2025.4.1
      helm:
        valueFiles:
          - $values/k8s/helm/authentik/values.yaml

    - repoURL: https://github.com/TodoFlow-Labs/infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
