---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    authentik-key: AgDHT4zhmaNn3rLkAK1iPdk3/tmKctKX/K5OF0kD3kT+C6tM79ukGnTgayBZwkHE+x1weyYqc/0+G0oH/kck960BO1ayR83G/LzuPLYOabi51PclUfIzTFY8G8A92/P0gLCzXoq15/q+mfkZHsILcrgX4r+qCPFFhh+gxZeBM92een5JrLKUYA7YjZY50jbGFRXlys9lMCH+ZVIBGwDamFpvL4yZoZyr6LMvFE9hA+FlHw13V5WM+4F540kwPN9xzVVn7KJkzb7l/FXXt6cIqkwXTUoeAj87Bu6/LzKmTBAA0CQCc0cSXvrhHyjhXJ+j9w+3x7XrIM/4hfq6AJzL4ABRKzIT8wgcEgRtvJnI5g6eMaZxCTfTKt7IkehF+PlseSkR9wzoRyI0uvNbAlqfutMB1l2DXL6yIqfT7lejDyzSsbgPw4PpoHdAPNZ+B3yu5SpkrrV1kP0v1BPvci/TI/wNAyyS+wW8bfxE5Wkk8zC5uuprUTnwpNlTHuBEv9w+ai/9U0pYkd4t4KrEVhr8nmk0AfmPaV60QbZyo428XuJVRcTjVw5IsMGYK0AEfhEJ45a508xfdAtpJKAUFfcPoR6or0u4mOUV0FRLiSmlRok+oxaTdKMlIw6Re/ilhbrFTd1O35Mx65nXDUctrkrT1Emj7KY9NrObz3SD0C5gndhZxh8m+fc6BvpQOAf7C3TkZfQZVU+LB0cEqu8baEZ57reIy7rb6+Rw9Cr76GhBjTufOaKxCw4vIR8HKpa4qJtvKg2ZHGDlhuc8YOhCRUD1yuo7
    db-password: AgBnrQvV+4cNVEood3Xpixa3dVyq7x05U0G/xU7b4R8IlFp2bcX36rDKOwJL0VPFg+YfW7RmAKnTlrR/VS42UHbe/C9qLv0ACGaX7et1D2cvQm4E5S2F09AyQ+oho8jLcCJWmd/245n4oYGkCHftPdLd6viHjQJVK3JUG12NDFlehVWYu0+5o0Gk0rXrIDUSHCK5bycpOgZNusoFcXVAmyDgtwzjpNz9X8iKNqZpt1fGo5Ku4R8FL1FWTPekvBMw2IJ3p5IIAPICB+arAJS7mFmjUwmKfLGhl177Fnrjsao8m25TbMJXeQajaBEHVcy1zt3amaA4u9CXjJi6jQcFhQfpqHnu2ugKqSI7WyjkTU1wWfIkP3YWiMHsrsr+1br5r7kh2w7zHRM7QfVP4hAfj+YHOIYblU+3iMKdd6FTElAZap4/jsfDHtQL1+R9z97WLeYhrF9JiRaOR5pyyyNqGQ4NjSslXdeSBiurWb9nL8+04ejcGUvJ0Y4cCQ9FrMgZUlitK5VDVxicCfM0nmqvH6bmVWmDXMObg/VwJJIgrX//BASYcNCESOrKXJvzc2r7KmL0SXT9BwrlEPZ4rsFF71VvDUwsUkDfxzr15g38Fyqa+ezrdt/WkqexYB+BpkbmY5JN47PoCtUfeJY83Cp1AtfWOoiANq1crTd51rkCoomffxZqCzI8Xm7YFRxbxg6jTy0W+Sph
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
