---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    authentik-key: AgCg85pVSPcySVRmAKdTU2FSIMZKXXS639102g5zLGFDr7YzSSOYmvkjvDprRdWCYC4GP8vlZu5jBBVdJBswmQnz6U8lih6EXhsOV27QYDWn1uPUfiWyVju6BII0MvkpG3ZSi3yysc+BAqXHYIasqR2O0v2HTENFcOL+u/EUDmyR8bCUb5MIb62VuZWL6Pme+lSI0pyHU91bRFUrMK3CYDFHeg/++VLPqWU/qbiNWP8behBAPIt9l236PqSVmxjOAoVvfsvYACFxkKZpHwyG8yMDVnVu5EDMYtN/ZzgpYz/eqnvelqpb8RsbN+hqOh/IZc8181Z8osJd2Bpv3GacA7HE00AyYMeTI9PY4GRZ9z9+a/K0uh+SGjJpsu04sV+6IqdQhQCtzc1NcuUUBuga/cwT1ghosOLSWeJk5ERvHgRD9Kx5ZsA/zCqmFIOdl2Xc7MINsY/eeYJeuWqUhCZFYYvog50g+lOT4tfGI4gPTojkrOueSjlTpDW9jOh7ERjjuZdn9lLoxmX9gBxdY7j+N49Lt7Q0rRNqJ7aXCuXZpCYqvWtLKkmqVQG/vmQolpc5bEc2xEjg9GpxN/FBg47W7KuwhRYPIg8r/XRwYzmgxFXzQR0II13uJEXERdLRNe7/IX30gcMWdLd0bco0SW2FgpRkXCEZVwbm7yM0KvCiDrDYKi3D3bbnwAoGHzE53DaR/ReuSb/umEe7jEiWDaZmFsaN4r7muwXX46pOE0rUTN8BuXAQPHvFC/Og3uwCw85WwuMuQ0f2/vPjmICSSUTrcchJ
    db-password: AgB8bLo+6+hsjlLs8rL7q/wNyw3kLNuEtIsGwOD3q3lYdap/Pr2L/q0LQ7SWBBwghFwr0T+xGe+dX0nBzAkpiS+i6mWFyupvGxkidjZZpDvLYAZNzwQzP8cnvGSjy0FovlRdw7y4eu3pW3ljdLnly3aRvqHDwMhA948qLkYxhGbaFrBjrJE2K/rsWUvaRugMG4HBgUyKmRJgKhcDhi8ouDNYW+i18ovIXrIYr2SuhylcLwL1EKEmoC0OF8qb8bi28j7eZVphJyX19jBvwXpg4zvFZU/2WWHLeKn/dBoWJ6rUYQV0k/0XErLOeWxBDuH1wbSmtIQjdlFmlbiWDovSDvBNTtDy44MBhBEv7ziaHGzlS3pYECd8B6CgS88GjBiWVZprnQhl8rw7C/h2Ed75nILEkmpv1JdMzhH/7jrz8qOMe/hCx+T7zwhUvD/D5J55YNM27xIQqln4E+OwNQHKwg+aekNwiwTef9u/rNNoQ4A6nR2AdDMhclvxhOSLoGQm+ZvvVje1A+Be22CO41FpLsTO1260Z9zWOWLtahvjWCrcpGNuxGvrgLDjP+hWLKZBHF6Qh5p3EWHI0JJkJGtrhdvoZAGCqBCZv4egw3gFlQizhgTrM/Bo5x6ezYgmJmRP/u+yz/3HnYgDXmBMYaAd4/nHNnpTs5gR/mGD5bLUh24T5gQettG9YizBoNOKwQWP9hlDgmOS
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
