---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB9Gt9KtsK+2DYaK7Hkq0PLFgHu4LJbqNPH70NeEiyXfnjAu5jf8Yr+2hJmiGiTFsJ9LXxVrzbdz747wpMmruNEdU0saOKSas2Oh1bAzKsVBpMxD1rLD3U3YRv63SLniP7oveg7SCWupblL7dMMNe0tQc6Y7JONlo6Yhr7WDOd7pJuc/u71hT7xvLPRMmm0ys3WRmE8iFigeh7m8os5PjpmUazUsr1HbS9ixgCRFAJpZEt38be4s1GJWanM+651w4uCYtsiQz8cnfyvQFg7tV6vnkiSIns69OSPRN9uWNS+G3ZkNrWvBreusm4FA0/FvyGmYvY2ghdzDMGyXS33i4nkRXQCgKenF4CJSFhfjPYalai8KCJg6S48L57IKHTDaxWvnlZmsnykqICUikpWpb10+24o/i8y3QE0Rtm+AL8fhyH/89B3WZl2XwCZ0nkpizgVOXbqHxyLYQN2vVN9+S/g3OIgFU1jZ9QlxdSQ2F9/SX1PTK97isEWWd0rI01wt5K1Mjs211JaoBhVRlKreOApn07JSUeTQ3doB1B6AqhXUMe6xhUCu8a9nNfMd3744b5LRgw+QDH0Ab9G/SXDGTbQgLdQYuZWGp8HjCUCc73HtXkWuMrfxH9V+GQaUVxJuoFPLs8MrrZUSH3VhN6TD4MKMP8L9WxApeFVdJwa2Nv2vSJjk3ZkdZ587uBIHfFyEs+7gJEpk2BJAQ==
    admin-user: AgAiUg7UQtk+n6Mel+OrnT/HPp1pxkqkgc7yxFh+kuEPYRpcVB6cj9tHMqR+FNMfKTDxQJn8FLv/Knq17BOQGNMBYowWHGBqZeZV7HqM9OAN9skX0PEgtJklz2tNT3a59FvGYRRc65hL+0jcl7jJEHsovrE4rmO8/aa5izSXaIC8uw6QV+z8F9RXj2ZXIQVi6MLPgznPMmIUJd0tFsKOgu17en8f8c+lmfMyB+VJ6J92P9Czy+1LP7Fc+J3kcA5iRXuC7P3GSCO1uF8ya2ruBsEqh1HK3H2e1bJjVyH1Wtopn7bTgMRuqpbiq9JpRubIrFSZlay4tjyKPDdXb2ERsqQMdCmpUP8hCgxnO2Mss/loxO2ryXrZNk19U4gqtiFFdKE3Ci7DHiEPXWB7NLmcHBnRoAP8zOz2xUAWZbO7jC/rLpj9aRGmEOWW5LVJFkRWQf9C5+dhRT4/I0B77Sw3poARDuo8r73m59aFFKYbu45UBexQgS6t1XudbYP87KKfyU9EEeg34zA2Bvy+fhcycVfMe1vIDPPLOPRQUVcniiB3m9kPxp4ZRKnosscm/D4GuNLEieb0qRjXX5eM/4o/uVz7Tk9ngF7+DVXg1ERgG2Yf/bBks0sNMfSKY5vMPXXMqFydZnbMZB+cRfC3uFP6cZ1wQEQ6hOLbL8P0/3qp6DDdYv+fMnGraYJ+5a3+zNHZcQfPqVzpkg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
