---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDRG1Ogdsz1TPg6la0D299vYdzNF3/dylV71UeInTG4VY9SY48DFZ925WWpBvr9XZP3fXX9wXqtrb5D+uF7ZrjgzeGxhQh2VfwlbXqFexvhR8oqEgLKS3o9if0JqwSTMbZuhAbK7LTNT+qo+mlQQUOY8zlak0yXH6oa4IqwyRnavVnsjF+QafoYoldw8Yno6oyYnTn0LP4hUtje/FFd8k3JWzRjf7k4A0qSazda8VxvBCnwbtluJP1y/fkUQppv/Z1An4Stm0MMg9azsDdsiLZYMOFNtEZ0KkrhUzxXU34WZrRsgmgxf3JDeZTsOlXswc7xdFAlvuKgktrBuI9fRfbiZef+gYOJmZPXP9ghw0IlAVovANkD6bT7LxktipwG/0PbxSWyd3Qj6T2tZUqf7VhVN951lVDXgUy79b7TO/49kU7XfvX69+e+8BCtcc9llgeE0rE6VcjFCVH7aB9M6aOhQrijEtkGCVXOx01CqKTcZpM//4u2Wa6FJDnmvo59ywytfcKQDxQY6J0jLtusZk0FHyskFV85L1eIc7x3JE1fp+PdmmOsqXYYFH0N6iA8ACWB6eRzhHiI8tap4xQodQ412A/FmB8P9h5VnAlt2GeI576RP7dEMjFVGPGzdHGaHSdSHxTVPcnqAZ5MqkNsWQHgYt9G97xDgTdESzwz7PKyR58vTNllM7Ck1ymAAxck9AE4b7fb0eD5nA==
    admin-user: AgBB9443IqV/u0X9O/g7pWe3rNBS4h6eq3b8Upo0FYvDCeylOVN90ldOoS5WW+dEisLHxcLW8F2chL8tEyYXy+DuI7FYW+Guu1PAOM8uDGHqcpc6dyr6G/qeSVBiGTfpxyxWCGMRhG0BKjpovypqu1UmIpAqQVvNWYqxn7iQPEy4wCM7Z5AvS3UtjoDRn5EFrxl8eMZRglE7kvrkjz6mEWdDGypihsqNLcEQlgAS9YbOwmOyUkaVEsY1f/KLpRW4PF5BA11eWAZkV33+rSAS5wWDgcMpMMv+Bqbs2lhHMEi9Rgj3Wi7nTFEHzkyyjmyusefdC6JpXidy9+nr7TWhYn8AHQ+j4kto66jlbJTeFSpfTZrVKrsWIzPJBguQSKWalb5QCq88L2HQPDxuxPewu5wkIh/tZ4BlTGO6S2i9fOfT7+TQZpkQOUu2vI7bBYw/dr7gqVBtEDftKxEuoP5HRutZBe8woGJ7zPG4LZryu6Owo390rLRFByltwKI+3NMxRr4sRVaJbmsEHLLD/NcrAkqw3BjjLlMFp8pR40tCn2khBnrZdiyc2nknsWL9An3FXO7QDV5DR87CpylKjzCVH4Xecr3GgKCidsq83vgnJ5A3BSKkRtC9LO4QhsdNm4wQq5Z5BU565TTEtpmmSmBjUxvZMtxwkuMYKB9osX6KOHGeXtNsNxad91dRdqHaUCfe7NOOMfxmpQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
