apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TodoFlow-Labs/infrastructure.git
    targetRevision: HEAD
    path: .
    helm:
      chart: grafana 
      repoURL: https://grafana.github.io/helm-charts
      version: 8.0.1
      valueFiles:
        - k8s/helm/grafana/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
