apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  sources:
    # 1. Istio base
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.26.0

    # 2. Istiod control plane
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.26.0
      helm:
        parameters:
          - name: meshConfig.accessLogFile
            value: "/dev/stdout"
        valueFiles:
          - $values/k8s/helm/istio/istiod-values.yaml

    # Local Git repo with Helm values
    - repoURL: https://github.com/TodoFlow-Labs/infrastructure.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
