apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  sources:
    # 1. Remote NATS Helm chart
    - repoURL: https://nats-io.github.io/k8s/helm/charts
      chart: nats
      targetRevision: 1.3.6 
      helm:
        valueFiles:
          - $values/k8s/helm/nats/values.yaml

    # 2. Your Git repo with the values file
    - repoURL: https://github.com/TodoFlow-Labs/infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true