apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TodoFlow-Labs/infrastructure.git
    targetRevision: HEAD
    path: k8s/helm/todoflow
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: todoflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
