apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    # 1. Remote Helm chart
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 35.2.0
      helm:
        valueFiles:
          - $values/k8s/helm/traefik/values.yaml

    # 2. Your repo with values.yaml
    - repoURL: https://github.com/TodoFlow-Labs/infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true