apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    # 1. Remote Helm chart
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 8.0.1
      helm:
        valueFiles:
          - $values/k8s/helm/grafana/values.yaml

    # 2. Git repo containing your custom values.yaml
    - repoURL: https://github.com/TodoFlow-Labs/infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true